---
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Enable and start Icinga
  service:
    name: icinga2
    enabled: "{{ icinga2_service_enabled }}"
    state: "{{ icinga2_service_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
