---
- hosts: all
  name: Prepare
  tasks:
    - name: Install required packages on Debian
      ansible.builtin.apt:
        name:
          # required to verify icinga2 is running
          - procps
        update_cache: true
      when: ansible_os_family == 'Debian'
