---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure Icinga 2 is installed
      ansible.builtin.stat:
        path: /usr/sbin/icinga2
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Ensure Icinga 2 is running
      ansible.builtin.command: pgrep -x icinga2
      changed_when: false
