---
name: Release

'on':
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: transitiv.icinga2

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: transitiv.icinga2

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: transitiv.icinga2

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install ansible-base

      - name: Trigger an import on Ansible Galaxy
        run: >
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          transitiv ansible-role-icinga2
